version: "3"

services:
  mongo:
    image: mongo
    volumes:
      - ./var/database:/data/db
      - ./scripts/mongo/init/:/docker-entrypoint-initdb.d
      - ./scripts/mongo/init:/home/mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=app

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root

  api:
    build:
      context: .
      dockerfile: api.dev.dockerfile
    ports:
      - 3000:3000
    links:
      - mongo:db
    volumes:
      - ./api:/app

  frontend:
    build:
      context: .
      dockerfile: frontend.dev.dockerfile
    ports:
      - 80:80
    volumes:
      - ./frontend:/app